---
title: "Homework 6"
author: "Emma Gagne"
date: "25 February 2021"
output: 
  html_document:
    theme: readable
---

# Problem 1

Assign to the variable n_dims a single random integer between 3 and 10.  
Input:
```
n_dims <- sample(3:10, 1)
print(n_dims)

> print(n_dims)
[1] 4
```

Create a vector of consecutive integers from 1 to n_dims2.  
Input:
```
con_int <- c(1:n_dims^2)
print(con_int)

> print(con_int)
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19
[20] 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
[39] 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
[58] 58 59 60 61 62 63 64
```

Use the sample function to randomly reshuffle these values.  
```
samp <- sample(con_int)
print(samp)

> print(samp)
 [1] 50 57 30  7  6 13 15 43 49 59 26 18 10 48 31 39 54 55 45
[20] 34 20 11  2 19 37 56 61  9 24 25 44 14 33 17 38  8 27 12
[39] 58  4 47  3 22 36 21 23 52 46 42 35 32 41 29 28 62 64  5
[58] 16  1 53 60 40 63 51
```

Create a square matrix with these elements.  
```
my_matrix <- matrix(samp,nrow=5,ncol=5)
```

Print out the matrix  
```
print(my_matrix)

> print(my_matrix)
    [,1] [,2] [,3] [,4] [,5]
[1,]   50   13   26   39   20
[2,]   57   15   18   54   11
[3,]   30   43   10   55    2
[4,]    7   49   48   45   19
[5,]    6   59   31   34   37
```

Find a function in r to transpose the matrix.  
```
transformed <- t(my_matrix)
```

Print it out again and note how it has changed.  
```
print(transformed)

> print(transformed)
[,1] [,2] [,3] [,4] [,5]
[1,]   50   57   30    7    6
[2,]   13   15   43   49   59
[3,]   26   18   10   48   31
[4,]   39   54   55   45   34
[5,]   20   11    2   19   37
```

Calculate the sum and the mean of the elements in the first row and the last row.  
```
sum(transformed[1,])
mean(transformed[1,])
sum(transformed[5,])
mean(transformed[5,])

> sum(transformed[1,])
[1] 150
> mean(transformed[1,])
[1] 30
> sum(transformed[5,])
[1] 89
> mean(transformed[5,])
[1] 17.8
```

Read about the eigen() function and use it on your matrix.  
```
eigen <- eigen(transformed, symmetric = TRUE, 
      only.values = FALSE,
      EISPACK = FALSE)
```
$values is a vector of values sorted in decreasing order.  
$vectors is a matrix of numbers bounded from -1 to 1.  

Dig in with the typeof() function to figure out their type.  
```
typeof(eigen$values) # it is a double
typeof(eigen$vectors) # it is a double
```


# Problem 2

Create a list with the following named elements;  
* my_matrix, which is a 4 x 4 matrix filled with random uniform values  
* my_logical which is a 100-element vector of TRUE or FALSE values. Do this efficiently by setting up a vector of random values and then applying an inequality to it.  
* my_letters, which is a 26-element vector of all the lower-case letters in random order.  

```
my_matrix <- matrix(data=runif(16),ncol=4,nrow=4)
my_matrix

> my_matrix
           [,1]      [,2]      [,3]      [,4]
[1,] 0.73675388 0.4485607 0.8146384 0.4272540
[2,] 0.09839652 0.8317704 0.4146723 0.8526894
[3,] 0.80235170 0.9370223 0.3865347 0.8462440
[4,] 0.85659344 0.1278849 0.7602438 0.2153246

my_vec <- c(1:100)
my_vec <- sample(my_vec)
my_logical <- my_vec < 50
my_logical

my_logical
  [1]  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE FALSE
 [10]  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE
 [19]  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE
 [28] FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE FALSE  TRUE
 [37]  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE
 [46]  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE FALSE FALSE
 [55]  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE
 [64] FALSE  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
 [73] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE
 [82] FALSE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE
 [91] FALSE FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE
[100] FALSE

my_letters <- c(LETTERS[1:26])
my_letters <- sample(my_letters)
my_letters

> my_letters
 [1] "R" "S" "Q" "B" "U" "J" "X" "O" "H" "Y" "I" "K" "T" "L"
[15] "D" "W" "C" "M" "V" "E" "P" "G" "F" "A" "N" "Z"

list <- list(my_matrix,my_logical,my_letters)
str(list)

> str(list)
List of 3
 $ : num [1:4, 1:4] 0.7368 0.0984 0.8024 0.8566 0.4486 ...
 $ : logi [1:100] TRUE FALSE FALSE TRUE FALSE TRUE ...
 $ : chr [1:26] "R" "S" "Q" "B" ...
```

Create a new list, which has the element[2,2] from the matrix, the second element of the logical vector, and the second element of the letters vector.  
```
new_list <- list(my_matrix[2,2],my_logical[2],my_letters[2])
new_list

> new_list
[[1]]
[1] 0.8317704

[[2]]
[1] FALSE

[[3]]
[1] "S"
```

Use the typeof() function to confirm the underlying data types of each component in this list.  
```
typeof(my_matrix[2,2]) # double
typeof(my_logical[2]) # logical
typeof(my_letters[2]) # Character
```

Combine the underlying elements from the new list into a single atomic vector with the c() function.  
```
new_vec <- c(my_matrix[2,2],my_logical[2],my_letters[2])
print(new_vec)

> [1] "0.8317704370711" "FALSE"           "S"   
```
What is the data type of this vector?  
```
typeof(new_vec)

> character
```


# Problem 3

Create a data frame with two variables (= columns) and 26 cases (= rows).

Call the first variable my_unis and fill it with 26 random uniform values from 0 to 10.  
```
my_unis <- runif(26,0,10)
my_unis

> my_unis
 [1] 3.7803745 9.9720143 3.7402164 7.4315575 5.9240743
 [6] 4.5669785 2.7894569 5.7041886 8.9943722 8.7508390
[11] 1.1617886 5.5721046 3.1601808 5.2045083 8.9140713
[16] 5.9827386 3.1869952 2.7580970 9.0610119 8.7725265
[21] 2.2085208 1.5753749 1.5717666 1.3305263 8.0036334
[26] 0.3290535
```

Call the second variable my_letters and fill it with 26 capital letters in random order.  
```
my_letters <- sample(LETTERS[1:26])
my_letters

> my_letters
 [1] "Q" "F" "H" "N" "W" "M" "C" "Y" "G" "V" "P" "I" "L" "D"
[15] "T" "X" "S" "K" "J" "A" "E" "O" "Z" "U" "B" "R"

data <- data.frame(my_unis,my_letters)
data

> data
     my_unis my_letters
1  3.7803745          Q
2  9.9720143          F
3  3.7402164          H
4  7.4315575          N
5  5.9240743          W
6  4.5669785          M
7  2.7894569          C
8  5.7041886          Y
9  8.9943722          G
10 8.7508390          V
11 1.1617886          P
12 5.5721046          I
13 3.1601808          L
14 5.2045083          D
15 8.9140713          T
16 5.9827386          X
17 3.1869952          S
18 2.7580970          K
19 9.0610119          J
20 8.7725265          A
21 2.2085208          E
22 1.5753749          O
23 1.5717666          Z
24 1.3305263          U
25 8.0036334          B
26 0.3290535          R
```

For the first variable, use a single line of code in R to select 4 random rows and replace the numerical values in those rows with NA.  
```
my_unis[sample(1:26,4)] <- NA
my_unis

> my_unis
 [1] 3.7803745 9.9720143 3.7402164 7.4315575 5.9240743
 [6] 4.5669785 2.7894569        NA 8.9943722 8.7508390
[11] 1.1617886 5.5721046        NA        NA 8.9140713
[16] 5.9827386 3.1869952 2.7580970        NA 8.7725265
[21] 2.2085208 1.5753749 1.5717666 1.3305263 8.0036334
[26] 0.3290535
```

For the first variable, write a single line of R code to identify which rows have the missing values.  
```
which(!complete.cases(my_unis))

> which(!complete.cases(my_unis))
[1]  8 13 14 19
```

For the second variable, sort it in alphabetical order.  
```
sort(my_letters)

> sort(my_letters)
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N"
[15] "O" "P" "Q" "R" "S" "T" "U" "V" "W" "X" "Y" "Z"
```

Calculate the column mean for the first variable.  
```
mean(my_unis, na.rm=TRUE)

> mean(my_unis, na.rm=TRUE)
[1] 4.878049
```